# Generated by Django 5.1.7 on 2025-05-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='pdf_thumbnails/'),
        ),
    ]
