# Generated by Django 5.2.1 on 2025-06-01 16:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0003_pdfdocument_category_pdfdocument_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='pdf'),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
